// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPermissionByCode = `-- name: GetPermissionByCode :one

SELECT id, code, description
FROM permissions
WHERE code = $1
`

type GetPermissionByCodeRow struct {
	ID          pgtype.UUID `json:"id"`
	Code        string      `json:"code"`
	Description string      `json:"description"`
}

// User Directory & Auth module store (AD-2), generated into package postgres
// by sqlc. These are the building blocks the auth port resolves identity and
// permission sets from (AD-12: additive union of permission-group memberships
// + direct grants). Story 1.1 ships the toolchain plus the first queries;
// later stories extend this file and re-run `just sqlc-generate`.
func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (GetPermissionByCodeRow, error) {
	row := q.db.QueryRow(ctx, getPermissionByCode, code)
	var i GetPermissionByCodeRow
	err := row.Scan(&i.ID, &i.Code, &i.Description)
	return i, err
}

const listPermissionGroupsByUser = `-- name: ListPermissionGroupsByUser :many
SELECT pg.id, pg.name, pg.description, pg.is_base_role
FROM permission_groups pg
JOIN user_permission_groups upg ON upg.permission_group_id = pg.id
WHERE upg.user_id = $1
ORDER BY pg.name
`

type ListPermissionGroupsByUserRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	IsBaseRole  bool        `json:"is_base_role"`
}

func (q *Queries) ListPermissionGroupsByUser(ctx context.Context, userID pgtype.UUID) ([]ListPermissionGroupsByUserRow, error) {
	rows, err := q.db.Query(ctx, listPermissionGroupsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionGroupsByUserRow
	for rows.Next() {
		var i ListPermissionGroupsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsBaseRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
